---
helm:
  # refresh versions from
  # https://github.com/helm/helm/releases
  version: 3.11.1
  version_command: helm version --short
  platform:
    Linux:
      url: https://get.helm.sh/helm-v3.11.1-linux-amd64.tar.gz
      checksum: sha256:0b1be96b66fab4770526f136f5f1a385a47c41923d33aab0dcb500e0f6c1bf7c
      unpack: true
    Darwin:
      url: https://get.helm.sh/helm-v3.11.1-darwin-amd64.tar.gz
      checksum: sha256:2548a90e5cc957ccc5016b47060665a9d2cd4d5b4d61dcc32f5de3144d103826
      unpack: true
helmfile:
  # refresh versions from
  # https://github.com/helmfile/helmfile/releases
  version: 0.151.0
  version_command: helmfile -v | awk '{print $3}'
  platform:
    Linux:
      url: https://github.com/helmfile/helmfile/releases/download/v0.151.0/helmfile_0.151.0_linux_amd64.tar.gz
      checksum: sha256:f33bdad8c1c7081cc95a858c4d307baf419f03d77758fae26ac8625725b398d9
      unpack: true
    Darwin:
      url: https://github.com/helmfile/helmfile/releases/download/v0.151.0/helmfile_0.151.0_darwin_amd64.tar.gz
      checksum: sha256:55128a0fc18f8f9f864eb5eeb53f94751a8f273c767122820bb51a10f02dba82
      unpack: true
