---
helm:
  # refresh versions from
  # https://github.com/helm/helm/releases
  url: https://get.helm.sh/helm-v3.17.2-linux-amd64.tar.gz
  download_checksum: sha256:90c28792a1eb5fb0b50028e39ebf826531ebfcf73f599050dbd79bab2f277241
  binary_checksum: 9e7a767efb3f9e334758ae066b4af355c01539663c7fffb30eed2b6213a4735e
  unpack: true
helmfile:
  # refresh versions from
  # https://github.com/helmfile/helmfile/releases
  url: https://github.com/helmfile/helmfile/releases/download/v0.171.0/helmfile_0.171.0_linux_amd64.tar.gz
  download_checksum: sha256:c190fd305307ea3fd41a91a95b3341100a1ede239cf32e225564a1ece286fb1b
  binary_checksum: 8bd28d832b6d9fde9e770925a03d251a7672737b3248293bf52c0b3dfcc64e73
  unpack: true
