---
helm:
  # refresh versions from
  # https://github.com/helm/helm/releases
  url: https://get.helm.sh/helm-v3.14.4-linux-amd64.tar.gz
  checksum: sha256:a5844ef2c38ef6ddf3b5a8f7d91e7e0e8ebc39a38bb3fc8013d629c1ef29c259
  unpack: true
helmfile:
  # refresh versions from
  # https://github.com/helmfile/helmfile/releases
  url: https://github.com/helmfile/helmfile/releases/download/v0.167.1/helmfile_0.167.1_linux_amd64.tar.gz
  checksum: sha256:245bfb3dae5df1c0a45a5e255d06823da98b0b41267dade84ae6815707c93315
  unpack: true
