---
k9s:
  # refresh versions from https://github.com/derailed/k9s/releases
  url: https://github.com/derailed/k9s/releases/download/v0.32.5/k9s_Linux_amd64.tar.gz
  checksum: sha256:33c31bf5feba292b59b8dabe5547cb52ab565521ee5619b52eb4bd4bf226cea3
  unpack: true
