---
kubectl:
  # refresh versions from
  # https://kubernetes.io/docs/tasks/tools/#kubectl
  url:
    amd64: https://dl.k8s.io/release/v1.30.13/bin/linux/amd64/kubectl
    arm64: https://dl.k8s.io/release/v1.30.13/bin/linux/arm64/kubectl
  checksum:
    amd64: sha256:b92bd89b27386b671841d5970b926b645c2ae44e5ca0663cff0f1c836a1530ee
    arm64: sha256:afed1753b98ab30812203cb469e013082b25502c864f2889e8a0474aac497064
  unpack: false
