---
kubectl:
  # refresh versions from
  # https://kubernetes.io/docs/tasks/tools/#kubectl
  url: https://dl.k8s.io/release/v1.30.13/bin/linux/amd64/kubectl
  checksum: sha256:b92bd89b27386b671841d5970b926b645c2ae44e5ca0663cff0f1c836a1530ee
  unpack: false
