---
kubectl:
  # refresh versions from
  # https://kubernetes.io/docs/tasks/tools/#kubectl
  version: 1.26.2
  version_command: kubectl version --client -o json | grep gitVersion | awk -F'v' '{print $2}' | tr -d \",
  url: https://dl.k8s.io/release/v1.26.2/bin/linux/amd64/kubectl
  checksum: sha256:fcf86d21fb1a49b012bce7845cf00081d2dd7a59f424b28621799deceb5227b3
  unpack: false
