---
lima_kilo_local_path: "{{ ansible_env.HOME }}"
lima_kilo_bin: "{{ lima_kilo_local_path }}/bin"

# the default docker network inside vagrant is 172.19.0.0/16 so take it as the default
# normally, docker0 will have 172.19.0.1 and that is reachable from within
# containers running in the local kubernetes
# Note that this is changed to the right ip by the install script for lima-vm
lima_kilo_docker_addr: "172.19.0.1"
