---
old_lima_kilo_local_path: "{{ ansible_env.HOME }}/.local/toolforge-lima-kilo"
lima_kilo_local_path: "{{ ansible_env.HOME }}/.toolforge-lima-kilo"
lima_kilo_userconfig: "{{ lima_kilo_local_path }}/userconfig.yaml"
lima_kilo_chroot: "{{ lima_kilo_local_path }}/chroot"
