---
lima_kilo_local_path: "{{ ansible_env.HOME }}"
lima_kilo_bin: "{{ lima_kilo_local_path }}/bin"
lima_kilo_repo: "{{ lima_kilo_local_path }}/lima-kilo"
lima_kilo_docker_addr: "{{ ansible_default_ipv4.address }}"
cache_disk_mount: "/mnt/lima-cache"
use_cache: "true"
