---
lima_kilo_bin: "{{ ansible_env.HOME }}/bin"
lima_kilo_repo: "{{ ansible_env.HOME }}/lima-kilo"
lima_kilo_docker_addr: "{{ ansible_default_ipv4.address }}"
cache_disk_mount: "/mnt/lima-cache"
use_cache: "true"
