---
stern:
  # refresh versions from https://github.com/stern/stern/releases
  url:
    amd64: "https://github.com/stern/stern/releases/download/v1.32.0/stern_1.32.0_linux_amd64.tar.gz"
    arm64: "https://github.com/stern/stern/releases/download/v1.32.0/stern_1.32.0_linux_arm64.tar.gz"
  checksum:
    amd64: "sha256:4733268b0e7fea48426c594d186be8cbcdb863858e08910451ebe3b1c8286f44"
    arm64: sha256:10b7ce269996547b08b524226d9c7678985b525232539e6e943ebe8475521615
  unpack: true
