---
# expected hash:
# conf:
#   shortname: string
#   repo_spec: string
#   key_url: string
#   packages:
#     - string

- name: install repository keys /etc/apt/trusted.gpg.d/{{ conf.shortname }}.asc
  become: true
  ansible.builtin.get_url:
    url: "{{ conf.key_url }}"
    dest: /etc/apt/trusted.gpg.d/{{ conf.shortname }}.asc
    mode: "0644"
  when: target == 'install'

- name: remove repository key for /etc/apt/trusted.gpg.d/{{ conf.shortname }}.asc
  become: true
  ansible.builtin.file:
    path: /etc/apt/trusted.gpg.d/{{ conf.shortname }}.asc
    state: absent
  when: target == 'uninstall'

- name: repository /etc/apt/sources.list/{{ conf.shortname }}.list "{{ 'present' if target == 'install' else 'absent' }}"
  become: true
  ansible.builtin.apt_repository:
    filename: "{{ conf.shortname }}"
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/{{ conf.shortname }}.asc] {{ conf.repo_spec }}
    state: "{{ 'present' if target == 'install' else 'absent' }}"
    update_cache: false

- name: update single repository defined in /etc/apt/sources.list.d/{{ conf.shortname }}.list
  become: true
  ansible.builtin.command:
    cmd: apt-get update -o Dir::Etc::sourcelist="/etc/apt/sources.list.d/{{ conf.shortname }}.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
  # never mark this task as changed (otherwise is always changed)
  changed_when: false
  when: target == 'install'

- name: ensure packages status "{{ 'latest' if target == 'install' else 'absent' }}"
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "{{ 'latest' if target == 'install' else 'absent' }}"
    update_cache: false
  loop: "{{ conf.packages }}"
