---
- name: Delete fake toolforge files
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ toolforge.files }}"

- name: Delete tool accounts unix users
  become: true
  ansible.builtin.user:
    name: "{{ toolforge.project_name }}.{{ tool_account.name }}"
    state: absent
  loop: "{{ toolforge.tool_accounts }}"
  loop_control:
    loop_var: tool_account
    label: "{{ tool_account.name }}"

- name: Delete tool accounts unix groups
  become: true
  ansible.builtin.group:
    name: "{{ toolforge.project_name }}.{{ tool_account.name }}"
    state: absent
  loop: "{{ toolforge.tool_accounts }}"
  loop_control:
    loop_var: tool_account
    label: "{{ tool_account.name }}"
