---
- name: Install stern binary
  ansible.builtin.include_tasks: "{{ role_path }}/../utils/tasks/install-binary-from-url.yaml"
  vars:
    binary:
      name: "stern"
      path: "{{ lima_kilo_bin }}/stern"
      url: "{{ stern.url }}"
      download_checksum: "{{ stern.download_checksum }}"
      binary_checksum: "{{ stern.binary_checksum }}"
      unpack: "{{ stern.unpack }}"
