---
- name: Install stern binary
  ansible.builtin.include_tasks: "{{ role_path }}/../utils/tasks/install-binary-from-url.yaml"
  vars:
    binary:
      name: "stern"
      path: "{{ lima_kilo_bin }}/stern"
      url: "{{ stern.url[install_arch] }}"
      checksum: "{{ stern.checksum[install_arch] }}"
      unpack: "{{ stern.unpack }}"
