---
- name: install a kind-based fake Toolforge in a Debian-based machine
  hosts: localhost
  vars:
    target: 'install'
  vars_files:
    - vars/kind.yaml
    - vars/toolforge.yaml
  roles:
    - { role: toolforge }
    - { role: kind }
    - { role: kubectl }
