---
- name: uninstall a kind-based fake Toolforge in a Debian-based machine
  hosts: localhost
  vars:
    target: uninstall
  vars_files:
    - vars/kind.yaml
    - vars/toolforge.yaml
  roles:
    - { role: kind }
    - { role: toolforge }
    - { role: kubectl }
    - { role: k8s }
