---
- name: Uninstall a kind-based fake Toolforge
  hosts: localhost
  vars:
    target: uninstall
  vars_files:
    - vars/lima-kilo.yaml
    - vars/kind.yaml
    - vars/toolforge.yaml
  roles:
    - { role: userconfig }
    - { role: kind }
    - { role: cli }
    - { role: toolforge }
    - { role: kubectl }
    - { role: helm }
    - { role: k8s }
