---
- name: install a kind-based fake Toolforge in a linux machine
  hosts: localhost
  vars:
    state: 'install'
  vars_files:
    - vars/kind.yaml
    - vars/toolforge.yaml
  roles:
    - { role: kind }
    - { role: toolforge }
