---
- name: uninstall a kind-based fake Toolforge in a linux machine
  hosts: localhost
  vars:
    state: 'uninstall'
  vars_files:
    - vars/kind.yaml
  roles:
    - { role: kind }
    - { role: toolforge }
