---
# we can't easily install the true `become` script, it is shipped in the `misctools` package,
# which is only served via aptly on a private address
# this allows to run `become tf-test` to become the user `local.tf-test`.
- name: Install become emulation
  become: true
  ansible.builtin.copy: # noqa template-instead-of-copy
    dest: "/usr/local/bin/become"
    content: |
      #!/bin/bash
      sudo -i -u local.${1}
    mode: "0755"
    owner: "root"
    group: "root"
